---
- name: Fetch the file from server1
  hosts: 172.31.22.198         
  tasks:
    - name: Fetch file
      fetch:
        src: file1
        dest: /tmp
- name: Copy file to server2
  hosts: 172.31.19.28
  tasks:
    - name: Copy file
      copy:
        src: /tmp/172.31.22.198/file1
        dest: /tmp

...          

